# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f5923a8ccb0a0e7bb0518c3a7989fd1fa4bc3968067ab04040134cdc17d37da66890b8eb131f08a2685b29f97c79b545fd68eb1d5d0a98944b7e32f55744ec1

test:
  secret_key_base: 848aaeb81412ed5bf379025a36d1f931f08538c100fe594d15f7f3d69bcca6b5bf12f1fc654a939904c16614a3bc52a573db89fe61ff3a5b81a45594d5ecafe1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
